POST http://localhost:4004/api/appointments
Content-Type: application/json

{
  "patientId": "7cd9a191-acb6-479d-9da6-c65880756847",
  "doctorName": "Dr. Strange",
  "appointmentTime": "2026-01-20T10:00:00"
}